services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./data/pxe-config/dnsmasq.conf:/etc/dnsmasq.conf:z
      - ./data/pxe-config/grub.cfg:/tftp/grub.cfg:z
      - ./data/os/EFI/BOOT/grubx64.efi:/tftp/grubx64.efi:z
      - ./data/os/images/pxeboot/initrd.img:/tftp/initrd.img:z
      - ./data/os/images/pxeboot/vmlinuz:/tftp/vmlinuz:z
    network_mode: host
    cap_add:
      - NET_ADMIN
  http:
    build: ./http
    network_mode: host
    volumes:
      - ./data/os:/usr/share/nginx/html/os:z
      - ./data/init-config/:/usr/share/nginx/html/init-config:z
    environment:
      NGINX_PORT: 80
