external-dns:
  provider: cloudflare
  txtOwnerId: homelab
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: value
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
  policy: sync
  interval: 5m
  triggerLoopOnEvent: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
