all:
  vars:
    control_plane_endpoint: 192.168.30.100
    load_balancer_ip_pool:
      - 192.168.30.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.30.110, mac: 'bc:24:11:94:36:4c', disk: sda, network_interface: ens18}
        metal1: {ansible_host: 192.168.30.111, mac: 'bc:24:11:a8:99:8e', disk: sda, network_interface: ens18}
        metal2: {ansible_host: 192.168.30.112, mac: 'bc:24:11:25:ed:26', disk: sda, network_interface: ens18}
    # workers:
    #   hosts:
    #     metal3: {ansible_host: 192.168.30.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
