apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-smb-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        username: hl0-immich
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: external
        property: immich_nfs_pass